# -*- coding: utf-8 -*
kind_name={'Early_pregnancy_bresult':{0:'未做',1:'已妊娠',2:'未妊娠',3:'不能确定',4:'其他'},
'Early_pregnancy_fola_method':{1:'规律服用',2:'不规律服用'},
'Early_pregnancy_folacin':{0:'未服用',1:'停经前至少3个月',2:'停经前1-2个月',3:'停经后'},
'Early_pregnancy_hcg':{0:'未做',1:'阳性',2:'阴性',3:'可疑'},
'Exam_bmod_result_type':{0:'正常',1:'异常',2:'不能确定'},
'Exam_drinking':{0:'否',1:'偶尔',2:'经常'},
'Exam_drinking_1':{0:'否',1:'偶尔',2:'经常'},
'Exam_dysmenorrhea':{0:'无',1:'轻',2:'重'},
'Exam_economic_pressure':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'},
'Exam_economic_pressure_1':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'},
'Exam_faccount_type':{1:'农业户口',2:'非农业户口'},
'Exam_fedu_level':{1:'文盲',2:'小学',3:'初中',4:'高中/中专/中技',5:'大专/大本',6:'研究生及以上'},
'Exam_fjob':{1:'农民',2:'工人',3:'服务业',4:'经商',5:'家务',6:'教师/公务员/职员等',7:'其他'},
'Exam_leu_cleanliness':{0:'I',1:'II',2:'III',3:'IV'},
'Exam_maccount_type':{1:'农业户口',2:'非农业户口'},
'Exam_medu_level':{1:'文盲',2:'小学',3:'初中',4:'高中/中专/中技',5:'大专/大本',6:'研究生及以上'},
'Exam_mens_quanti':{0:'无',1:'多',2:'中',3:'少'},
'Exam_mjob':{1:'农民',2:'工人',3:'服务业',4:'经商',5:'家务',6:'教师/公务员/职员等',7:'其他'},
'Exam_orchis':{0:'睾丸扪及',1:'左侧未扪及',2:'右侧未扪及',3:'双侧未扪及'},
'Exam_prepuce':{0:'正常',1:'过长',2:'包茎'},
'Exam_pressure':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'},
'Exam_pressure_1':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'},
'Exam_second_hand_smoking':{0:'否',1:'偶尔',2:'经常'},
'Exam_second_hand_smoking_1':{0:'否',1:'偶尔',2:'经常'},
'Exam_tense_relationship':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'},
'Exam_tense_relationship_1':{0:'无',1:'很少',2:'有一点',3:'比较大',4:'很大'}}



di_nationalty = {
    '资料不详': '-1',
    '傈傈族': '傈僳族',
    '傈族': '傈僳族',
    '其他族族': '其他族',
    '回': '回族',
    '族': '-1',
    '未分类民族': '其他族',
    '未识别族': '其他族',
    '汉': '汉族',
    '汉字': '汉族',
    '满': '满族',
    '男': '-1',
    '维族': '维吾尔族',
    '蒙古': '蒙古族',
    '蒙族': '蒙古族',
    '穿青人族': '穿青族'
}

di_province = {
    '66203广东': '广东省',
    '0027湖南': '湖南省',
    '927431466广东': '广东省',
    '内蒙古': '内蒙古自治区',
    '天津': '天津市',
    '云南': '云南省',
    '吉林': '吉林省',
    '四川': '四川省',
    '培训省级': '-1',
    '宁夏': '宁夏回族自治区',
    '宁夏自治区': '宁夏回族自治区',
    '安微': '安徽省',
    '安徽': '安徽省',
    '山东': '山东省',
    '山西': '山西省',
    '广东': '广东省',
    '广西': '广西壮族自治区',
    '广西省': '广西壮族自治区',
    '江苏': '江苏省',
    '江西': '江西省',
    '河北': '河北省',
    '河南': '河南省',
    '浙江': '浙江省',
    '海南': '海南省',
    '湖北': '湖北省',
    '湖南': '湖南省',
    '甘肃': '甘肃省',
    '福建': '福建省',
    '西安': '陕西省',
    '西藏': '西藏自治区',
    '贵州': '贵州省',
    '辽宁': '辽宁省',
    '重庆': '重庆市',
    '重庆省': '重庆市',
    '陕西': '陕西省',
    '黑龙江': '黑龙江省',
    '新疆': '新疆维吾尔自治区',
    '沈阳市': '辽宁省',
    '甘肃市': '甘肃省',
    '西藏省': '西藏自治区',
    '井陉': '河北省',
    '北京': '北京市',
    '北省': '-1',
    '培训省级': '-1',
    '天津': '天津市',
    '安徽': '安徽省',
    '广东': '广东省',
    '新乐': '河北省',
    '河南': '河南省',
    '济南': '山东省',
    '石家': '河北省',
    '贵州': '贵州省',
    '辛集': '河北省',
    '郑州': '河南省',
    '长寿': '重庆市'
}

di_city = {
    '保山': '保山市',
    '省直辖县': '-1',
    '省直辖县级行政区划': '-1',
    '自治区直辖县级行政区划': '-1',
    '县': '-1',
    '市': '-1',
    '市辖区': '-1',
    '广州': '广州市',
    '开封': '开封市',
    '恩施州': '恩施土家族苗族自治州',
    '毕节': '毕节市',
    '毕节地区': '毕节市',
    '洛阳': '洛阳市',
    '深圳': '深圳市',
    '滁州': '滁州市',
    '铜仁地区': '铜仁市'
}

provice_id={'河南省': 1, '海南省': 2, '北京市': 3, '新疆维吾尔自治区': 4, '陕西省': 5, '重庆市': 6, '浙江省': 8, '新疆生产建设兵团': 17, '吉林省': 29, '山西省': 10, '青海省': 11, '广西壮族自治区': 12, '天津市': 13, '宁夏回族自治区': 14, '江西省': 15, '安徽省': 16, '河北省': 9, '福建省': 18, '广东省': 19, '湖南省': 20, '云南省': 21, '江苏省': 22, '甘肃省': 23, '山东省': 24, '四川省': 25, '上海市': 26, '辽宁省': 27, '内蒙古自治区': 28, '湖北省': 7, '贵州省': 30, '黑龙江省': 31, '西藏自治区': 32}

henan_no_city=['Exam_chronic_nephritis_1',
'Exam_province',
'Exam_use_medicine',
'Exam_abo_f_ab',
'Exam_thyroid_disease_1',
'Exam_contracept_stop',
'Exam_sexually_infect_1',
'Exam_hbc_ab_1',
'Exam_abo_m_ab',
'Exam_epilepsy_1',
'Exam_contracept_others',
'Exam_oral_contraceptive',
'Exam_heart_disease_1',
'Exam_anemia_1',
'Exam_swelling_1',
'Exam_contracept',
'Exam_hypertension_1',
'Exam_urine_routine_1',
'Exam_nodule_1',
'Exam_bad_pregnancy_result',
'Exam_second_hand_smoking',
'Exam_faccount_type',
'Exam_condom',
'Exam_topical_contraceptives',
'Exam_second_hand_smoking_box',
'Exam_orchis',
'Exam_is_ill_1',
'Exam_subcutaneous_implants',
'Exam_natural_contracept',
'Exam_economic_pressure',
'Exam_tense_relationship',
'Exam_pressure',
'Exam_urine_routine',
'Exam_intrauterine_device',
'Exam_prepuce',
'Exam_economic_pressure_1',
'Exam_rv_igg',
'Exam_leu_trichomonas',
'Exam_pressure_1',
'Exam_child_ill',
'Exam_fjob',
'Exam_short_mouth_num',
'Exam_leu_monilial',
'Exam_abo_m_a',
'Exam_vaccinate_1',
'Exam_baby_num',
'Exam_vaccinate',
'Exam_abo_f_a',
'Exam_abo_f_o',
'Exam_vaccinate_others',
'Exam_indu_abor_num',
'Exam_mjob',
'Exam_yigan',
'Exam_vaccinate_others_1',
'Exam_yigan_1',
'Exam_fengzhen_1',
'Exam_abo_m_o',
'Exam_abo_f_b',
'Exam_smoking_1',
'Exam_abo_m_b',
'Exam_live_birth_num',
'Exam_second_hand_smoking_1',
'Exam_enou_month_num',
'Exam_hbs_ab',
'Exam_breed_history',
'Exam_hbs_ab_1',
'Exam_second_hand_smoking_box_1',
'Exam_pre_num',
'Exam_cv_igg',
'Exam_dysmenorrhea',
'Exam_leuph',
'Exam_drinking_1',
'Exam_leu_amine_odor',
'Exam_drinking_box_1',
'Exam_fengzhen',
'Exam_favism',
'Exam_tense_relationship_1',
'Exam_contracept_period',
'Exam_menses_regular',
'Exam_leu_cleanliness',
'Exam_smoking_box_1',
'Exam_medu_level',
'Exam_fedu_level',
'Exam_first_time_age',
'Early_pregnancy_fola_method',
'Early_pregnancy_hcg',
'Exam_mens_period_max',
'Exam_mens_period',
'Exam_leu_clue_cell',
'Exam_mens_cycle_max',
'Exam_low_blood_pressure',
'Exam_height_1',
'Early_pregnancy_bresult',
'Exam_height',
'Exam_mens_cycle',
'Exam_low_blood_pressure_1',
'Exam_hight_blood_pressure',
'Exam_hight_blood_pressure_1',
'Exam_weight_1',
'Exam_weight',
'Early_pregnancy_folacin',
'Exam_heart_rate',
'Exam_heart_rate_1',
'Exam_be',
'Exam_alt',
'Exam_bb',
'Exam_alt_1',
'Exam_blood_sugar',
'Exam_bmi_1',
'Exam_bmi',
'Exam_bm',
'Exam_bplt',
'Exam_bwbc',
'Exam_bhb',
'Exam_f_age',
'Exam_tsh',
'Exam_bn',
'Exam_m_age',
'Exam_cr_1',
'Early_pregnancy_sure_mens_time',
'Exam_brbc',
'Exam_bl',
'Exam_cr',
'Exam_right_orchis_palpable_capacity',
'Exam_midcell',
'Exam_left_orchis_palpable_capacity']

henan_raw_feature=['Exam_abo_m_b', 'Exam_fjob', 'Exam_abo_m_o', 'Exam_hbs_ab_1', 'Exam_topical_contraceptives', 'Exam_hbs_ab', 'Exam_dysmenorrhea', 'Exam_economic_pressure_1', 'Exam_yigan_1', 'Exam_vaccinate_1', 'Exam_second_hand_smoking_1', 'Exam_vaccinate_others_1', 'Exam_pressure_1', 'Exam_breed_history', 'Exam_vaccinate', 'Exam_yigan', 'Exam_vaccinate_others', 'Exam_favism', 'Exam_enou_month_num', 'Exam_fengzhen_1', 'Exam_live_birth_num', 'Exam_drinking_1', 'Exam_pre_num', 'Exam_leuph', 'Exam_leu_cleanliness', 'Exam_tense_relationship_1', 'Exam_fengzhen', 'Exam_smoking_box_1', 'Exam_leu_amine_odor', 'Exam_contracept_period', 'Early_pregnancy_hcg', 'Early_pregnancy_fola_method', 'Exam_first_time_age', 'Exam_mens_period_max', 'Exam_medu_level', 'Exam_leu_clue_cell', 'Exam_menses_regular', 'Exam_mens_period', 'Early_pregnancy_bresult', 'Exam_fedu_level', 'Exam_mens_cycle', 'Exam_low_blood_pressure', 'Exam_height_1', 'Exam_height', 'Exam_mens_cycle_max', 'Exam_hight_blood_pressure', 'Exam_be', 'Exam_low_blood_pressure_1', 'Exam_bb', 'Exam_hight_blood_pressure_1', 'Early_pregnancy_folacin', 'Exam_weight', 'Exam_weight_1', 'Exam_heart_rate', 'Exam_bm', 'Exam_heart_rate_1', 'Exam_alt', 'Exam_alt_1', 'Exam_bmi', 'Exam_bmi_1', 'Exam_bplt', 'Exam_blood_sugar', 'Exam_bwbc', 'Exam_bhb', 'Exam_f_age', 'Exam_tsh', 'Exam_m_age', 'Exam_bn', 'Early_pregnancy_sure_mens_time', 'Exam_cr_1', 'Exam_bl', 'Exam_right_orchis_palpable_capacity', 'Exam_cr', 'Exam_brbc', 'Exam_left_orchis_palpable_capacity', 'Exam_midcell','Exam_province']


process_dic={'Early_pregnancy_bresult': ['B超结果', 4.0, 0],
 'Early_pregnancy_fola_method': ['服用叶酸的方法', 1.0, 0],
 'Early_pregnancy_folacin': ['服用叶酸及开始时间', 3.0, 0],
 'Early_pregnancy_hcg': ['尿妊娠试验结果', 3.0, 0],
 'Early_pregnancy_sure_mens_time': ['末次月经是否准确', 0, 0],
 'Exam_abo_f_a': ['(女方)血型-A型', 0, 0],
 'Exam_abo_f_ab': ['(女方)血型-AB型', 0, 0],
 'Exam_abo_f_b': ['(女方)血型-B型', 0, 0],
 'Exam_abo_f_o': ['(女方)血型-O型', 0, 0],
 'Exam_abo_m_a': ['(男方)血型-A型', 0, 1],
 'Exam_abo_m_ab': ['(男方)血型-AB型', 0, 1],
 'Exam_abo_m_b': ['(男方)血型-B型', 0, 1],
 'Exam_abo_m_o': ['(男方)血型-O型', 0, 1],
 'Exam_abo_rh': ['(女方)血型-Rh', 0, 0],
 'Exam_abor_num': ['自然流产次数', -1, 0],
 'Exam_address_city': ['妻子现住址――市', -1, 0],
 'Exam_address_county': ['妻子现住址――县', -1, 0],
 'Exam_address_province': ['妻子现住址――省', -1, 0],
 'Exam_albinism': ['(女方或家族成员)患有白化病', 0, 0],
 'Exam_albinism_1': ['(男方或家族成员)患有白化病', 0, 1],
 'Exam_alt': ['(女方)谷丙转氨酶（ALT） u/L', -1, 0],
 'Exam_alt_1': ['(男方)谷丙转氨酶', -1, 1],
 'Exam_anemia': ['(女方)患有贫血', 0, 0],
 'Exam_anemia_1': ['(男方)患有贫血', 0, 1],
 'Exam_baby_num': ['现有子女数', -1, 0],
 'Exam_bad_pregnancy_result': ['(女方)有不良妊娠结局(死产死胎，自然流产，人工流产)', 0, 0],
 'Exam_bb': ['(女方)血细胞分析(B )  %', -1, 0],
 'Exam_be': ['(女方)血细胞分析(E)   %', -1, 0],
 'Exam_bhb': ['(女方)血细胞分析(Hb)   g/L', -1, 0],
 'Exam_bl': ['(女方)血细胞分析(L)   %', -1, 0],
 'Exam_blood_sick': ['(女方或家族成员)患有血有病', 0, 0],
 'Exam_blood_sick_1': ['(男方或家族成员)患有血有病', 0, 1],
 'Exam_blood_sugar': ['(女方)血糖  mmol/L', -1, 0],
 'Exam_bm': ['(女方)血细胞分析(M )  %', -1, 0],
 'Exam_bmi': ['(女方)体重指数', -1, 0],
 'Exam_bmi_1': ['(男方)体重指数', -1, 1],
 'Exam_bmod_result_type': ['(女方)是否正常', 3.0, 0],
 'Exam_bn': ['(女方)血细胞分析(N)  %', -1, 0],
 'Exam_bplt': ['(女方)血细胞分析(PLT)  ×109/L', -1, 0],
 'Exam_brbc': ['(女方)血细胞分析(RBC)  1012/L', -1, 0],
 'Exam_breast': ['(女方)乳房', 0, 0],
 'Exam_breed_history': ['(女方)曾经怀孕：0：否，1：是', 0, 0],
 'Exam_buge_monggon': ['(男方)喉结', 0, 1],
 'Exam_bwbc': ['(女方)血细胞分析(WBC)  ×1012/L', -1, 0],
 'Exam_caculate': ['(女方)计算', 0, 0],
 'Exam_caculate_1': ['(男方)计算', 0, 1],
 'Exam_catdog': ['(女方)接触猫狗', 0, 0],
 'Exam_catdog_1': ['(男方)接触猫狗', 0, 1],
 'Exam_child_ill': ['子女身体状况', 0, 0],
 'Exam_chlamydiat': ['(女方)沙眼衣原体筛查', 0, 0],
 'Exam_chronic_nephritis': ['(女方)患有慢性肾炎', 0, 0],
 'Exam_chronic_nephritis_1': ['(男方)患有慢性肾炎', 0, 1],
 'Exam_condom': ['(女方)正在使用或曾经使用避孕套', 0, 0],
 'Exam_congenital_heart_disease': ['(女方或家族成员)患有先天性心脏病', 0, 0],
 'Exam_congenital_heart_disease_1': ['(男方或家族成员)患有先天性心脏病', 0, 1],
 'Exam_contracept': ['(女方)正在使用或曾经使用（以下7种至少一种）避孕措施', 0, 0],
 'Exam_contracept_others': ['(女方)正在使用或曾经使用其他避孕措施', 0, 0],
 'Exam_contracept_period': ['避孕措施持续使用时间(月数)', -1, 0],
 'Exam_contracept_stop': ['停止避孕措施', 0, 0],
 'Exam_cr': ['(女方)肌酐（Cr） u/L', -1, 0],
 'Exam_cr_1': ['(男方)肌酐', -1, 1],
 'Exam_cv_igg': ['(女方)巨细胞病毒(IgG)', 0, 0],
 'Exam_cv_igm': ['(女方)巨细胞病毒(IgM)', 0, 0],
 'Exam_dangr_obj': ['医生判断', -1, -1],
 'Exam_dead_birth_num': ['死产死胎次数', -1, 0],
 'Exam_diabetes': ['(女方)患有糖尿病', 0, 0],
 'Exam_diabetes1': ['(女方或家族成员)患有糖尿病', 0, 0],
 'Exam_diabetes1_1': ['(男方或家族成员)患有糖尿病', 0, 1],
 'Exam_diabetes_1': ['(男方)患有糖尿病', 0, 1],
 'Exam_disease_history_f': ['(女方)本人或家族成员有人患有以下疾病', 0, 0],
 'Exam_disease_history_f_1': ['(男方)本人或家族成员有人患有以下疾病', 0, 1],
 'Exam_disease_history_f_others': ['(女方)患有有其他病', 0, 0],
 'Exam_disease_history_f_others_1': ['(男方)患有其他病', 0, 1],
 'Exam_down_syndrome': ['(女方或家族成员)患有唐氏综合症', 0, 0],
 'Exam_down_syndrome_1': ['(男方或家族成员)患有唐氏综合症', 0, 1],
 'Exam_drinking': ['(女方)饮酒情况', 2.0, 0],
 'Exam_drinking_1': ['(男方)饮酒情况', 2.0, 1],
 'Exam_drinking_box': ['(女方)饮酒量（每天_____ml）', -1, 0],
 'Exam_drinking_box_1': ['(男方)饮酒量（每天_____ml）', -1, 1],
 'Exam_drug': ['(女方)使用毒麻药品', 0, 0],
 'Exam_drug_1': ['(男方)使用毒麻药品', 0, 1],
 'Exam_dysgnosia': ['(女方或家族成员)患有智力障碍', 0, 0],
 'Exam_dysgnosia_1': ['(男方或家族成员)患有智力障碍', 0, 1],
 'Exam_dysmenorrhea': ['痛经', 2.0, 0],
 'Exam_economic_pressure': ['(女方)感到经济压力', 4.0, 0],
 'Exam_economic_pressure_1': ['(男方)感到经济压力', 4.0, 1],
 'Exam_enou_month_num': ['足月活产次数', -1, 0],
 'Exam_epididymis': ['(男方)附睾正常', 0, 1],
 'Exam_epilepsy': ['(女方)患有癫痫', 0, 0],
 'Exam_epilepsy_1': ['(男方)患有癫痫', 0, 1],
 'Exam_f_age': ['(女方)孕龄', -1, 0],
 'Exam_faccount_loaction_province': ['女方户口所在地――省', -1, 0],
 'Exam_faccount_location_city': ['女方户口所在地――市', -1, 0],
 'Exam_faccount_location_county': ['女方户口所在地――县', -1, 0],
 'Exam_faccount_type': ['女方户口性质', 1.0, 0],
 'Exam_facial_features': ['(女方)五官', 0, 0],
 'Exam_facial_features_1': ['(男方)五官', 0, 1],
 'Exam_favism': ['(女方或家族成员)患有蚕豆病(G6PD缺乏症)', 0, 0],
 'Exam_favism_1': ['(男方或家族成员)患有蚕豆病(G6PD缺乏症)', 0, 1],
 'Exam_fedu_level': ['女方文化程度', 6.0, 0],
 'Exam_fengzhen': ['(女方)注射风疹疫苗', 0, 0],
 'Exam_fengzhen_1': ['(男方)注射风疹疫苗', 0, 1],
 'Exam_first_time_age': ['(女方)初潮年龄', -1, 0],
 'Exam_fjob': ['女方职业', 7.0, 0],
 'Exam_fnationalty': ['女方民族', -1, 0],
 'Exam_gonorrhoeae': ['(女方)淋球菌筛查', 0, 0],
 'Exam_gum_bleeding': ['(女方)牙龈出血', 0, 0],
 'Exam_halitosis': ['(女方)口臭', 0, 0],
 'Exam_hate_veg': ['(女方)厌食蔬菜', 0, 0],
 'Exam_hate_veg_1': ['(男方)厌食蔬菜', 0, 1],
 'Exam_hb': ['(女方)患有乙型肝炎', 0, 0],
 'Exam_hb_1': ['(男方)患有乙型肝炎', 0, 1],
 'Exam_hbc_ab': ['(女方)HBc-Ab', 0, 0],
 'Exam_hbc_ab_1': ['(男方)HBc-Ab', 0, 1],
 'Exam_hbe_ab': ['(女方)HBe-Ab', 0, 0],
 'Exam_hbe_ab_1': ['(男方)HBe-Ab', 0, 1],
 'Exam_hbe_ag': ['(女方)HBe-Ag', 0, 0],
 'Exam_hbe_ag_1': ['(男方)HBe-Ag', 0, 1],
 'Exam_hbs_ab': ['(女方)HBs-Ab', 0, 0],
 'Exam_hbs_ab_1': ['(男方)HBs-Ab', 0, 1],
 'Exam_hbs_ag': ['(女方)HBs-Ag', 0, 0],
 'Exam_hbs_ag_1': ['(男方)HBs-Ag', 0, 1],
 'Exam_hearing_disorder': ['(女方或家族成员)患有听力障碍', 0, 0],
 'Exam_hearing_disorder_1': ['(男方或家族成员)患有听力障碍', 0, 1],
 'Exam_heart_disease': ['(女方)患有心脏病', 0, 0],
 'Exam_heart_disease_1': ['(男方)患有心脏病', 0, 1],
 'Exam_heart_rate': ['(女方)心率 （次/分）', -1, 0],
 'Exam_heart_rate_1': ['(男方)心率 （次/分）', -1, 1],
 'Exam_heart_rhythm': ['(女方)心脏节律是否整齐', 0, 0],
 'Exam_heart_rhythm_1': ['(男方)心脏节律是否整齐', 0, 1],
 'Exam_heartmurmur': ['(女方)心脏是否有杂音', 0, 0],
 'Exam_heartmurmur_1': ['(男方)心脏是否有杂音', 0, 1],
 'Exam_height': ['(女方)身高（cm）', -1, 0],
 'Exam_height_1': ['(男方)身高（cm）', -1, 1],
 'Exam_high_temperature': ['(女方)接触高温', 0, 0],
 'Exam_high_temperature_1': ['(男方)接触高温', 0, 1],
 'Exam_hight_blood_pressure': ['(女方)血压高压值（ /mmHg）', -1, 0],
 'Exam_hight_blood_pressure_1': ['(男方)血压高压值（ /mmHg）', -1, 1],
 'Exam_hypertension': ['(女方)患有高血压', 0, 0],
 'Exam_hypertension_1': ['(男方)患有高血压', 0, 1],
 'Exam_indu_abor_num': ['人流次数', -1, 0],
 'Exam_infant_mortality': ['(女方或家族成员)新生儿或婴幼儿死亡', 0, 0],
 'Exam_infant_mortality_1': ['(男方或家族成员)新生儿或婴幼儿死亡', 0, 1],
 'Exam_intermarry': ['(女方)夫妻近亲结婚情况', 0, 0],
 'Exam_intermarry_f': ['(女方)祖父母/外祖父母、父母两代家族内近亲结婚史', 0, 0],
 'Exam_intermarry_f_1': ['(男方)祖父母/外祖父母、父母两代家族内近亲结婚史', 0, 1],
 'Exam_intrauterine_device': ['(女方)正在使用或曾经使用宫内节育器', 0, 0],
 'Exam_is_born_ill': ['(女方)患有出生缺陷,如先天畸形、遗传病等', 0, 0],
 'Exam_is_born_ill_1': ['(男方)患有出生缺陷,如先天畸形、遗传病等', 0, 1],
 'Exam_is_ill': ['(女方)患有或曾患疾病', 0, 0],
 'Exam_is_ill_1': ['(男方)患有或曾患疾病', 0, 1],
 'Exam_judge': ['(女方)判断', 0, 0],
 'Exam_judge_1': ['(男方)判断', 0, 1],
 'Exam_knowledge': ['(女方)常识', 0, 0],
 'Exam_knowledge_1': ['(男方)常识', 0, 1],
 'Exam_lead_hg': ['(女方)接触铅、汞', 0, 0],
 'Exam_lead_hg_1': ['(男方)接触铅、汞', 0, 1],
 'Exam_left_orchis_palpable_capacity': ['(男方)睾丸左侧扪及体积', -1, 1],
 'Exam_leu_amine_odor': ['(女方)白带检查-胺臭味实验', 0, 0],
 'Exam_leu_cleanliness': ['(女方)白带检查-清洁度', 3.0, 0],
 'Exam_leu_clue_cell': ['(女方)白带检查-线索细胞', 0, 0],
 'Exam_leu_monilial': ['(女方)白带检查-念珠菌感染', 0, 0],
 'Exam_leu_trichomonas': ['(女方)白带检查-滴虫感染', 0, 0],
 'Exam_leuph': ['(女方)白带检查-PH值', 0, 0],
 'Exam_live_birth_num': ['活产次数', -1, 0],
 'Exam_liver': ['(男方)肝', 0, 1],
 'Exam_low_blood_pressure': ['(女方)血压低压值（/mmHg）', -1, 0],
 'Exam_low_blood_pressure_1': ['(男方)血压低压值（/mmHg）', -1, 1],
 'Exam_lung': ['(女方)肺部', 0, 0],
 'Exam_lung_1': ['(男方)肺部', 0, 1],
 'Exam_m_age': ['(男方)孕龄', -1, 1],
 'Exam_maccount_loaction_province': ['男方户口所在地――省', -1, 1],
 'Exam_maccount_location_city': ['男方户口所在地――市', -1, 1],
 'Exam_maccount_location_county': ['女方户口所在地――县', -1, 0],
 'Exam_maccount_type': ['男方户口性质', 1.0, 1],
 'Exam_meategg': ['(女方)进食肉、蛋类', 0, 0],
 'Exam_meategg_1': ['(男方)进食肉、蛋类', 0, 1],
 'Exam_medu_level': ['男方文化程度', 6.0, 1],
 'Exam_memory': ['(女方)记忆', 0, 0],
 'Exam_memory_1': ['(男方)记忆', 0, 1],
 'Exam_mens_cycle': ['周期（下限）', -1, 0],
 'Exam_mens_cycle_max': ['周期（上限）', -1, 0],
 'Exam_mens_period': ['经期(下限)', -1, 0],
 'Exam_mens_period_max': ['经期(上限)', -1, 0],
 'Exam_mens_quanti': ['月经量', 3.0, 0],
 'Exam_menses_regular': ['月经是否规律', 0, 0],
 'Exam_micro_sp': ['(女方)梅毒螺旋体筛查', 0, 0],
 'Exam_midcell': ['(女方)中值细胞%', -1, 0],
 'Exam_mjob': ['男方职业', 7.0, 1],
 'Exam_mnationality': ['男方民族', -1, 1],
 'Exam_mumps_1': ['(男方)患有腮腺炎', 0, 1],
 'Exam_natural_contracept': ['(女方)正在使用或曾经使用自然避孕', 0, 0],
 'Exam_new_decoration': ['(女方)新装修', 0, 0],
 'Exam_new_decoration_1': ['(男方)新装修', 0, 1],
 'Exam_nodule': ['(女方)患有结核', 0, 0],
 'Exam_nodule_1': ['(男方)患有结核', 0, 1],
 'Exam_noise': ['(女方)接触噪音', 0, 0],
 'Exam_noise_1': ['(男方)接触噪音', 0, 1],
 'Exam_oral_contraceptive': ['(女方)正在使用或曾经使用口服避孕药', 0, 0],
 'Exam_orchis': ['(男方)睾丸', 3.0, 1],
 'Exam_orchitis_1': ['(男方)患有、附睾炎', 0, 1],
 'Exam_other_bad_pregnancy_results_num': ['其他不良妊娠结局的次数', -1, 0],
 'Exam_penis': ['(男方)阴茎', 0, 1],
 'Exam_pesticide': ['(女方)接触农药', 0, 0],
 'Exam_pesticide_1': ['(男方)接触农药', 0, 1],
 'Exam_pre_num': ['怀孕次数', -1, 0],
 'Exam_pregnancy_ready': ['(女方)做好怀孕准备', 0, 0],
 'Exam_pregnancy_ready_1': ['(男方)做好怀孕准备', 0, 1],
 'Exam_prepuce': ['(男方)包皮', 2.0, 1],
 'Exam_pressure': ['(女方)感到生活/工作压力', 4.0, 0],
 'Exam_pressure_1': ['(男方)感到生活/工作压力', 4.0, 1],
 'Exam_province': ['省份', -1, 0],
 'Exam_psy_disorder': ['(女方)患有精神心理病患', 0, 0],
 'Exam_psy_disorder_1': ['(男方)患有精神心理病患', 0, 1],
 'Exam_psycology': ['(女方)精神状况', 0, 0],
 'Exam_psycology_1': ['(男方)精神状况', 0, 1],
 'Exam_pubes': ['(女方)阴毛', 0, 0],
 'Exam_pubes_1': ['(男方)阴毛', 0, 1],
 'Exam_radial': ['(女方)接触射线', 0, 0],
 'Exam_radial_1': ['(男方)接触射线', 0, 1],
 'Exam_raw_meat': ['(女方)有食用生肉嗜好', 0, 0],
 'Exam_raw_meat_1': ['(男方)有食用生肉嗜好', 0, 1],
 'Exam_retardation': ['(女方)有无智力障碍', 0, 0],
 'Exam_retardation_1': ['(男方)有无智力障碍', 0, 1],
 'Exam_rh': ['(男方)血型-Rh', 0, 0],
 'Exam_right_orchis_palpable_capacity': ['(男方)睾丸右侧扪及体积', -1, 1],
 'Exam_rv_igg': ['(女方)风疹病毒(IgG)', 0, 0],
 'Exam_sd_child': ['(女方)分娩过出生缺陷儿', 0, 0],
 'Exam_second_hand_smoking': ['(女方)存在被动吸烟', 2.0, 0],
 'Exam_second_hand_smoking_1': ['(男方)存在被动吸烟', 2.0, 1],
 'Exam_second_hand_smoking_box': ['(女方)平均每天被动吸烟时间(分钟)', -1, 0],
 'Exam_second_hand_smoking_box_1': ['(男方)平均每天被动吸烟时间(分钟)', -1, 1],
 'Exam_secretions': ['(女方)分泌物', 0, 0],
 'Exam_seeing_disorder': ['(女方或家族成员)患有视力障碍', 0, 0],
 'Exam_seeing_disorder_1': ['(男方或家族成员)患有视力障碍', 0, 1],
 'Exam_seminal_duct': ['(男方)输精管正常', 0, 1],
 'Exam_sexually_infect': ['(女方)患有淋病/梅毒/衣原体感染等', 0, 0],
 'Exam_sexually_infect_1': ['(男方)患有淋病/梅毒/衣原体感染等', 0, 1],
 'Exam_shake': ['(女方)接触震动', 0, 0],
 'Exam_shake_1': ['(男方)接触震动', 0, 1],
 'Exam_short_mouth_num': ['早产次数', -1, 0],
 'Exam_shuffling_gait': ['(女方)四肢', 0, 0],
 'Exam_shuffling_gait_1': ['(男方)四肢', 0, 1],
 'Exam_skin': ['(女方)皮肤毛发', 0, 0],
 'Exam_skin_1': ['(男方)皮肤毛发', 0, 1],
 'Exam_smoking': ['(女方)吸烟情况', 0, 0],
 'Exam_smoking_1': ['(男方)吸烟情况', 0, 1],
 'Exam_smoking_box': ['(女方)吸烟次数（每天_____支）', -1, 0],
 'Exam_smoking_box_1': ['(男方)吸烟次数（每天_____支）', -1, 1],
 'Exam_special_body': ['(女方)特殊体型', 0, 0],
 'Exam_special_body_1': ['(男方)特殊体型', 0, 1],
 'Exam_specisal_look': ['(女方)有无特殊面容', 0, 0],
 'Exam_specisal_look_1': ['(男方)有无特殊面容', 0, 1],
 'Exam_sterility': ['(女方)不孕不育', 0, 0],
 'Exam_sterility_1': ['(男方)不孕不育', 0, 1],
 'Exam_subclinical_varicocele': ['(男方)精索静脉曲张', 0, 1],
 'Exam_subcutaneous_implants': ['(女方)正在使用或曾经使用皮下埋植剂', 0, 0],
 'Exam_swelling': ['(女方)患有肿瘤', 0, 0],
 'Exam_swelling_1': ['(男方)患有肿瘤', 0, 1],
 'Exam_tense_relationship': ['(女方)与亲友、同事的关系紧张程度', 4.0, 0],
 'Exam_tense_relationship_1': ['(男方)亲友、同事的关系紧张', 4.0, 1],
 'Exam_tg_igg': ['(女方)弓形虫 (IgG)', 0, 0],
 'Exam_tg_igm': ['(女方)弓形虫IgM', 0, 0],
 'Exam_thalassaemia': ['(女方或家族成员)患有地中海贫血', 0, 0],
 'Exam_thalassaemia_1': ['(男方或家族成员)患有地中海贫血', 0, 1],
 'Exam_thyroid': ['(女方)甲状腺', 0, 0],
 'Exam_thyroid_1': ['(男方)甲状腺', 0, 1],
 'Exam_thyroid_disease': ['(女方)患有甲状腺疾病', 0, 0],
 'Exam_thyroid_disease_1': ['(男方)患有甲状腺疾病', 0, 1],
 'Exam_topical_contraceptives': ['(女方)正在使用或曾经使用外用避孕药', 0, 0],
 'Exam_tpha': ['(男方)梅素螺旋体筛查', 0, 1],
 'Exam_tsh': ['(女方)促甲状腺激素（TSH） uIu/ml', -1, 0],
 'Exam_urine_routine': ['(女方)尿常规', 0, 0],
 'Exam_urine_routine_1': ['(男方)尿常规', 0, 1],
 'Exam_use_medicine': ['(女方)服药情况', 0, 0],
 'Exam_use_medicine_1': ['(男方)服药情况', 0, 1],
 'Exam_uterine': ['(女方)患有子宫附炎症', 0, 0],
 'Exam_uterus_act': ['(女方)子宫 活动', 0, 0],
 'Exam_uterus_adnexa': ['(女方)子宫双侧附件(输卵管和卵巢)', 0, 0],
 'Exam_uterus_bump': ['(女方)子宫 包块', 0, 0],
 'Exam_uterus_size_big': ['(女方)子宫-大', 0, 0],
 'Exam_uterus_size_small': ['(女方)子宫-小', 0, 0],
 'Exam_vaccinate': ['(女方)注射疫苗情况', 0, 0],
 'Exam_vaccinate_1': ['(男方)注射疫苗情况', 0, 1],
 'Exam_vaccinate_others': ['(女方)注射其他疫苗', 0, 0],
 'Exam_vaccinate_others_1': ['(男方)注射其他疫苗', 0, 1],
 'Exam_vagina': ['(女方)阴道', 0, 0],
 'Exam_varicose_veins_1': ['(男方)患有静脉曲张', 0, 1],
 'Exam_vervix': ['(女方)宫颈', 0, 0],
 'Exam_viver': ['(女方)肝', 0, 0],
 'Exam_vulva': ['(女方)外阴', 0, 0],
 'Exam_weight': ['(女方)体重（Kg）', -1, 0],
 'Exam_weight_1': ['(男方)体重（Kg）', -1, 1],
 'Exam_yigan': ['(女方)注射乙肝疫苗', 0, 0],
 'Exam_yigan_1': ['(男方)注射乙肝疫苗', 0, 1],
 'Outcome_bornfault': ['出生缺陷', -1, -1],
 'Outcome_deathpre': ['死胎死产', -1, -1],
 'Outcome_differentpre': ['异位妊娠', -1, -1],
 'Outcome_earlypre': ['早产', -1, -1],
 'Outcome_lower_weight': ['低出生体重', -1, -1],
 'Outcome_medicinepre': ['医学性人工流产', -1, -1],
 'Outcome_natrualpre': ['自然流产', -1, -1],
 'Outcome_normalpre': ['正常活产', -1, -1],
 'Outcome_qitapre': ['其他', -1, -1],
 'Outcome_treatpre': ['治疗性引产', -1, -1]}
provice_heap=[[5, 6, 7, 8, 9, 12, 13, 14, 22, 23, 24, 28, 29, 32], [11, 16, 17, 18, 25], [2, 3, 15, 27, 31],  [19],[10], [20]]
# 'Exam_faccount_loaction_province', 'Exam_address_province', 'Exam_maccount_loaction_province', 'Exam_fnationalty', 'Exam_mnationality',
feature_all_no_city=['Exam_hight_blood_pressure',
 'Exam_shuffling_gait',
 'Exam_hearing_disorder_1',
 'Exam_thyroid_1',
 'Exam_anemia',
 'Exam_catdog_1',
 'Exam_right_orchis_palpable_capacity',
 'Exam_topical_contraceptives',
 'Exam_uterus_bump',
 'Exam_swelling',
 'Exam_heart_rhythm',
 'Exam_bm',
 'Exam_favism',
 'Exam_down_syndrome_1',
 'Exam_orchis',
 'Exam_is_ill_1',
 'Exam_epididymis',
 'Exam_m_age',
 'Exam_intermarry_f_1',
 'Exam_judge',
 'Exam_facial_features_1',
 'Exam_thyroid',
 'Exam_drinking_box',
 'Exam_leu_cleanliness',
 'Exam_mjob',
 'Exam_drug',
 'Exam_low_blood_pressure',
 'Exam_dysgnosia_1',
 'Early_pregnancy_folacin',
 'Exam_leu_monilial',
 'Exam_shake_1',
 'Exam_subclinical_varicocele',
 'Exam_drug_1',
 'Exam_maccount_type',
 'Exam_mens_cycle',

 'Exam_f_age',
 'Exam_epilepsy_1',
 'Exam_abo_f_a',
 'Exam_hbs_ag_1',
 'Exam_second_hand_smoking_box',
 'Exam_height_1',
 'Exam_noise_1',
 'Exam_hbs_ag',
 'Exam_blood_sick_1',
 'Exam_second_hand_smoking_box_1',
 'Exam_economic_pressure_1',
 'Exam_dysgnosia',
 'Exam_economic_pressure',
 'Exam_mens_cycle_max',
 'Exam_uterine',
 'Exam_tg_igm',
 'Exam_yigan_1',
 'Exam_contracept_period',
 'Exam_high_temperature',
 'Exam_diabetes',
 'Exam_radial_1',
 'Exam_rh',
 'Exam_dead_birth_num',
 'Exam_leu_amine_odor',
 'Exam_drinking',
 'Exam_intermarry_f',
 'Exam_breast',
 'Exam_is_born_ill',
 'Exam_halitosis',
 'Exam_abo_m_b',
 'Exam_tense_relationship_1',
 'Exam_skin_1',
 'Exam_bmi',
 'Exam_hb_1',
 'Exam_special_body',
 'Exam_viver',
 'Exam_noise',
 'Exam_medu_level',
 'Exam_shuffling_gait_1',
 'Exam_abo_f_ab',
 'Exam_vaccinate',
 'Exam_disease_history_f_1',
 'Exam_fjob',
 'Exam_new_decoration',
 'Exam_second_hand_smoking_1',
 'Exam_smoking_box',
 'Exam_pregnancy_ready',
 'Exam_infant_mortality_1',
 'Exam_intrauterine_device',
 'Exam_psycology',
 'Exam_heart_rate_1',
 'Exam_vaccinate_1',
 'Exam_indu_abor_num',
 'Exam_sterility_1',
 'Exam_heartmurmur_1',
 'Exam_sexually_infect_1',
 'Exam_hypertension',
 'Exam_radial',
 'Exam_is_ill',
 'Exam_menses_regular',
 'Exam_dysmenorrhea',
 'Exam_bhb',
 'Exam_orchitis_1',
 'Exam_caculate_1',
 'Exam_heart_rate',
 'Exam_anemia_1',
 'Exam_leu_clue_cell',
 'Exam_disease_history_f',
 'Exam_abo_rh',
 'Exam_specisal_look_1',
 'Exam_hearing_disorder',
 'Early_pregnancy_fola_method',
 'Exam_hbe_ag',
 'Exam_lead_hg',
 'Exam_leu_trichomonas',
 'Exam_pregnancy_ready_1',
 'Exam_special_body_1',
 'Exam_hypertension_1',
 'Early_pregnancy_hcg',
 'Exam_tsh',
 'Exam_favism_1',
 'Exam_hate_veg',
 'Exam_gonorrhoeae',
 'Exam_use_medicine',
 'Exam_hb',
 'Exam_left_orchis_palpable_capacity',
 'Early_pregnancy_sure_mens_time',
 'Exam_nodule_1',
 'Exam_heart_rhythm_1',
 'Exam_liver',
 'Exam_chlamydiat',
 'Early_pregnancy_bresult',
 'Exam_vagina',
 'Exam_albinism_1',
 'Exam_short_mouth_num',
 'Exam_congenital_heart_disease_1',
 'Exam_is_born_ill_1',
 'Exam_hbe_ag_1',
 'Exam_hbs_ab',
 'Exam_uterus_act',
 'Exam_nodule',
 'Exam_other_bad_pregnancy_results_num',
 'Exam_second_hand_smoking',

 'Exam_micro_sp',
 'Exam_live_birth_num',
 'Exam_judge_1',
 'Exam_sexually_infect',
 'Exam_mens_period',
 'Exam_congenital_heart_disease',
 'Exam_shake',
 'Exam_bad_pregnancy_result',
 'Exam_condom',
 'Exam_pubes_1',
 'Exam_penis',
 'Exam_sterility',
 'Exam_blood_sick',
 'Exam_epilepsy',
 'Exam_contracept_others',
 'Exam_natural_contracept',
 'Exam_abo_f_o',
 'Exam_retardation_1',
 'Exam_down_syndrome',
 'Exam_abo_f_b',
 'Exam_be',
 'Exam_memory',
 'Exam_bwbc',
 'Exam_enou_month_num',
 'Exam_tense_relationship',
 'Exam_weight',
 'Exam_infant_mortality',
 'Exam_gum_bleeding',
 'Exam_smoking_box_1',
 'Exam_meategg',
 'Exam_fengzhen_1',
 'Exam_bl',
 'Exam_meategg_1',
 'Exam_pesticide_1',
 'Exam_pre_num',
 'Exam_psycology_1',
 'Exam_diabetes_1',
 'Exam_child_ill',
 'Exam_chronic_nephritis',
 'Exam_lung',
 'Exam_vaccinate_others',
 'Exam_bn',
 'Exam_abo_m_ab',
 'Exam_first_time_age',
 'Exam_height',

 'Exam_hbe_ab_1',
 'Exam_smoking_1',
 'Exam_drinking_box_1',
 'Exam_thyroid_disease',
 'Exam_varicose_veins_1',
 'Exam_hbe_ab',
 'Exam_mens_quanti',
 'Exam_thyroid_disease_1',
 'Exam_drinking_1',
 'Exam_hbc_ab',
 'Exam_raw_meat',
 'Exam_brbc',
 'Exam_cr_1',
 'Exam_psy_disorder',
 'Exam_facial_features',
 'Exam_vaccinate_others_1',
 'Exam_pesticide',
 'Exam_uterus_adnexa',
 'Exam_fengzhen',
 'Exam_hight_blood_pressure_1',
 'Exam_diabetes1_1',
 'Exam_bmod_result_type',
 'Exam_uterus_size_big',
 'Exam_lung_1',
 'Exam_uterus_size_small',

 'Exam_vervix',
 'Exam_leuph',
 'Exam_retardation',
 'Exam_faccount_type',
 'Exam_abo_m_a',
 'Exam_tg_igg',
 'Exam_lead_hg_1',
 'Exam_knowledge',
 'Exam_cv_igg',
 'Exam_mens_period_max',
 'Exam_use_medicine_1',
 'Exam_province',
 'Exam_disease_history_f_others_1',
 'Exam_hbc_ab_1',
 'Exam_catdog',
 'Exam_bmi_1',
 'Exam_contracept_stop',
 'Exam_chronic_nephritis_1',
 'Exam_seeing_disorder_1',
 'Exam_yigan',
 'Exam_smoking',
 'Exam_buge_monggon',
 'Exam_fedu_level',
 'Exam_oral_contraceptive',
 'Exam_low_blood_pressure_1',
 'Exam_high_temperature_1',
 'Exam_bplt',
 'Exam_bb',
 'Exam_raw_meat_1',
 'Exam_pubes',
 'Exam_heart_disease_1',
 'Exam_breed_history',
 'Exam_abor_num',
 'Exam_seminal_duct',
 'Exam_heart_disease',
 'Exam_subcutaneous_implants',
 'Exam_swelling_1',
 'Exam_contracept',

 'Exam_disease_history_f_others',
 'Exam_diabetes1',
 'Exam_thalassaemia',
 'Exam_cr',
 'Exam_rv_igg',
 'Exam_albinism',
 'Exam_skin',
 'Exam_hate_veg_1',
 'Exam_cv_igm',
 'Exam_pressure_1',
 'Exam_new_decoration_1',
 'Exam_baby_num',
 'Exam_urine_routine',
 'Exam_caculate',
 'Exam_memory_1',
 'Exam_psy_disorder_1',
 'Exam_seeing_disorder',
 'Exam_thalassaemia_1',
 'Exam_blood_sugar',
 'Exam_intermarry',
 'Exam_pressure',
 'Exam_secretions',
 'Exam_alt_1',
 'Exam_alt',
 'Exam_tpha',
 'Exam_vulva',
 'Exam_hbs_ab_1',
 'Exam_mumps_1',
 'Exam_heartmurmur',
 'Exam_urine_routine_1',
 'Exam_prepuce',
 'Exam_sd_child',
 'Exam_weight_1',
 'Exam_knowledge_1',
 'Exam_midcell',
 'Exam_specisal_look',
 'Exam_abo_m_o']

feature_all=['Exam_fengzhen', 'Exam_knowledge_1', 'Exam_infant_mortality', 'Exam_lung', 'Exam_address_county', 'Exam_leuph', 'Exam_tsh', 'Exam_raw_meat_1', 'Exam_abo_f_o', 'Exam_penis', 'Exam_orchitis_1', 'Exam_leu_amine_odor', 'Exam_pesticide', 'Exam_hbc_ab', 'Exam_contracept_stop', 'Exam_psy_disorder_1', 'Exam_abo_m_a', 'Exam_seeing_disorder', 'Exam_drinking', 'Exam_abor_num', 'Exam_vaccinate_others', 'Exam_cv_igg', 'Exam_tg_igg', 'Exam_second_hand_smoking_box_1', 'Exam_breed_history', 'Exam_fengzhen_1', 'Exam_subcutaneous_implants', 'Exam_hight_blood_pressure', 'Exam_second_hand_smoking_box', 'Exam_liver', 'Exam_diabetes_1', 'Exam_hate_veg', 'Exam_second_hand_smoking', 'Exam_down_syndrome', 'Exam_special_body', 'Exam_first_time_age', 'Exam_fjob', 'Exam_high_temperature_1', 'Exam_hbe_ab', 'Exam_seminal_duct', 'Exam_sterility', 'Exam_second_hand_smoking_1', 'Exam_thalassaemia', 'Exam_psycology_1', 'Exam_disease_history_f_others_1', 'Exam_shake_1', 'Exam_anemia', 'Exam_bl', 'Exam_bn', 'Exam_meategg_1', 'Exam_favism', 'Exam_maccount_location_county', 'Exam_skin', 'Exam_diabetes', 'Exam_intermarry_f_1', 'Exam_psycology', 'Exam_province', 'Exam_new_decoration', 'Exam_orchis', 'Exam_heart_disease_1', 'Exam_mens_cycle', 'Exam_abo_f_ab', 'Exam_hb', 'Exam_leu_trichomonas', 'Exam_address_province', 'Exam_pressure_1', 'Exam_hbs_ag', 'Exam_vaccinate_1', 'Exam_chronic_nephritis_1', 'Exam_maccount_type', 'Exam_cv_igm', 'Exam_congenital_heart_disease_1', 'Exam_infant_mortality_1', 'Exam_disease_history_f_1', 'Exam_favism_1', 'Exam_diabetes1_1', 'Exam_epilepsy_1', 'Exam_is_ill', 'Exam_smoking_box', 'Exam_tense_relationship', 'Exam_uterus_bump', 'Exam_sterility_1', 'Exam_blood_sugar', 'Exam_heartmurmur_1', 'Exam_retardation_1', 'Exam_drinking_box', 'Exam_disease_history_f', 'Exam_uterus_act', 'Exam_gonorrhoeae', 'Exam_hate_veg_1', 'Exam_hbs_ag_1', 'Exam_alt', 'Exam_hypertension', 'Exam_yigan', 'Exam_judge', 'Early_pregnancy_bresult', 'Early_pregnancy_fola_method', 'Exam_abo_m_o', 'Exam_tpha', 'Exam_heart_rate_1', 'Exam_vagina', 'Exam_buge_monggon', 'Exam_abo_m_b', 'Exam_bad_pregnancy_result', 'Exam_uterus_size_big', 'Exam_drinking_1', 'Exam_sexually_infect', 'Exam_leu_monilial', 'Exam_viver', 'Exam_dead_birth_num', 'Exam_disease_history_f_others', 'Exam_shake', 'Early_pregnancy_hcg', 'Exam_oral_contraceptive', 'Exam_subclinical_varicocele', 'Exam_noise', 'Exam_hypertension_1', 'Exam_new_decoration_1', 'Exam_abo_m_ab', 'Exam_diabetes1', 'Exam_memory_1', 'Exam_hb_1', 'Exam_tense_relationship_1', 'Exam_varicose_veins_1', 'Exam_pre_num', 'Exam_bmi_1', 'Exam_mens_period_max', 'Exam_economic_pressure_1', 'Exam_hbe_ab_1', 'Exam_swelling_1', 'Exam_weight', 'Exam_baby_num', 'Exam_intrauterine_device', 'Exam_low_blood_pressure', 'Early_pregnancy_sure_mens_time', 'Exam_address_city', 'Exam_hbs_ab_1', 'Exam_cr', 'Exam_chlamydiat', 'Exam_gum_bleeding', 'Exam_vervix', 'Exam_topical_contraceptives', 'Exam_thalassaemia_1', 'Exam_abo_rh', 'Exam_f_age', 'Exam_leu_cleanliness', 'Exam_caculate_1', 'Exam_natural_contracept', 'Exam_faccount_location_county', 'Exam_smoking_box_1', 'Exam_raw_meat', 'Exam_prepuce', 'Exam_thyroid_1', 'Exam_catdog_1', 'Exam_skin_1', 'Exam_fnationalty', 'Exam_intermarry_f', 'Exam_hbc_ab_1', 'Exam_nodule', 'Exam_epilepsy', 'Exam_indu_abor_num', 'Exam_memory', 'Exam_abo_f_b', 'Exam_contracept', 'Exam_urine_routine', 'Exam_contracept_period', 'Exam_rh', 'Exam_yigan_1', 'Exam_hbe_ag_1', 'Early_pregnancy_folacin', 'Exam_weight_1', 'Exam_hight_blood_pressure_1', 'Exam_brbc', 'Exam_blood_sick', 'Exam_faccount_type', 'Exam_low_blood_pressure_1', 'Exam_uterus_adnexa', 'Exam_anemia_1', 'Exam_chronic_nephritis', 'Exam_congenital_heart_disease', 'Exam_shuffling_gait', 'Exam_mumps_1', 'Exam_psy_disorder', 'Exam_down_syndrome_1', 'Exam_knowledge', 'Exam_bmod_result_type', 'Exam_hearing_disorder', 'Exam_urine_routine_1', 'Exam_drug_1', 'Exam_blood_sick_1', 'Exam_retardation', 'Exam_faccount_location_city', 'Exam_bm', 'Exam_heart_disease', 'Exam_right_orchis_palpable_capacity', 'Exam_use_medicine', 'Exam_breast', 'Exam_sexually_infect_1', 'Exam_heart_rate', 'Exam_midcell', 'Exam_use_medicine_1', 'Exam_menses_regular', 'Exam_high_temperature', 'Exam_lung_1', 'Exam_radial', 'Exam_specisal_look', 'Exam_bplt', 'Exam_smoking_1', 'Exam_facial_features_1', 'Exam_pesticide_1', 'Exam_lead_hg_1', 'Exam_hbe_ag', 'Exam_swelling', 'Exam_hbs_ab', 'Exam_leu_clue_cell', 'Exam_bwbc', 'Exam_height', 'Exam_uterus_size_small', 'Exam_is_ill_1', 'Exam_dysgnosia', 'Exam_medu_level', 'Exam_nodule_1', 'Exam_rv_igg', 'Exam_heart_rhythm_1', 'Exam_caculate', 'Exam_meategg', 'Exam_specisal_look_1', 'Exam_cr_1', 'Exam_condom', 'Exam_drinking_box_1', 'Exam_epididymis', 'Exam_halitosis', 'Exam_m_age', 'Exam_albinism', 'Exam_catdog', 'Exam_pregnancy_ready', 'Exam_heartmurmur', 'Exam_uterine', 'Exam_thyroid', 'Exam_seeing_disorder_1', 'Exam_faccount_loaction_province', 'Exam_albinism_1', 'Exam_vaccinate_others_1', 'Exam_shuffling_gait_1', 'Exam_sd_child', 'Exam_fedu_level', 'Exam_radial_1', 'Exam_thyroid_disease', 'Exam_pubes_1', 'Exam_mnationality', 'Exam_smoking', 'Exam_mens_quanti', 'Exam_noise_1', 'Exam_pregnancy_ready_1', 'Exam_dysgnosia_1', 'Exam_dysmenorrhea', 'Exam_heart_rhythm', 'Exam_mens_cycle_max', 'Exam_secretions', 'Exam_pubes', 'Exam_vulva', 'Exam_enou_month_num', 'Exam_bhb', 'Exam_contracept_others', 'Exam_judge_1', 'Exam_height_1', 'Exam_maccount_loaction_province', 'Exam_bb', 'Exam_bmi', 'Exam_thyroid_disease_1', 'Exam_maccount_location_city', 'Exam_alt_1', 'Exam_be', 'Exam_is_born_ill_1', 'Exam_vaccinate', 'Exam_mjob', 'Exam_lead_hg', 'Exam_facial_features', 'Exam_micro_sp', 'Exam_live_birth_num', 'Exam_tg_igm', 'Exam_abo_f_a', 'Exam_pressure', 'Exam_short_mouth_num', 'Exam_child_ill', 'Exam_intermarry', 'Exam_economic_pressure', 'Exam_mens_period', 'Exam_other_bad_pregnancy_results_num', 'Exam_hearing_disorder_1', 'Exam_is_born_ill', 'Exam_drug', 'Exam_special_body_1', 'Exam_left_orchis_palpable_capacity']

col_result=['Outcome_earlypre', 'Outcome_differentpre', 'Exam_dangr_obj',
       'Outcome_natrualpre', 'Outcome_medicinepre', 'Outcome_lower_weight',
       'Outcome_treatpre', 'Outcome_qitapre', 'Outcome_deathpre',
       'Outcome_bornfault', 'Outcome_normalpre']
#第一次选的
col_new=['Exam_smoking_1','Exam_leu_clue_cell','Exam_vaccinate_1','Exam_yigan_1'
,'Exam_pressure','Exam_yigan','Exam_vaccinate_others'
,'Exam_bad_pregnancy_result','Exam_vaccinate','Exam_abo_m_o'
,'Exam_drinking_1','Exam_dysmenorrhea','Exam_fengzhen_1','Exam_fengzhen'
,'Exam_pressure_1','Exam_hbs_ab_1'
,'Exam_child_ill','Exam_rv_igg','Exam_baby_num','Exam_hbs_ab'
,'Exam_bmod_result_type','Exam_leuph'
,'Exam_enou_month_num','Exam_cv_igg','Exam_fnationalty','Exam_mnationality'
,'Early_pregnancy_fola_method','Exam_mjob','Exam_medu_level'
,'Exam_breed_history','Exam_leu_cleanliness','Exam_fedu_level'
,'Exam_contracept_period','Exam_smoking_box_1','Exam_fjob'
,'Exam_first_time_age','Exam_pre_num','Exam_live_birth_num'
,'Early_pregnancy_hcg','Exam_mens_cycle_max','Exam_mens_period_max'
,'Exam_be','Exam_bb','Exam_mens_period','Exam_mens_cycle'
,'Early_pregnancy_sure_mens_time','Exam_low_blood_pressure','Exam_height'
,'Exam_bm','Exam_height_1','Exam_low_blood_pressure_1'
,'Exam_hight_blood_pressure','Early_pregnancy_bresult'
,'Exam_hight_blood_pressure_1','Exam_weight_1','Exam_heart_rate'
,'Exam_weight','Exam_heart_rate_1','Exam_right_orchis_palpable_capacity'
,'Exam_left_orchis_palpable_capacity','Early_pregnancy_folacin','Exam_alt'
,'Exam_bmi_1','Exam_midcell','Exam_alt_1','Exam_bmi','Exam_bwbc'
,'Exam_blood_sugar','Exam_cr_1','Exam_bhb','Exam_bplt','Exam_cr','Exam_tsh'
,'Exam_bn','Exam_m_age','Exam_bl','Exam_f_age','Exam_brbc'
,'Exam_faccount_loaction_province','Exam_maccount_loaction_province'
,'Exam_address_province','Exam_province',
 'Exam_address_city','Exam_address_county',
'Exam_faccount_location_city','Exam_faccount_location_county',
'Exam_maccount_location_city','Exam_maccount_location_county']

col_new_all_place=['Exam_fnationalty','Exam_mnationality',
'Exam_address_province','Exam_address_city','Exam_address_county',
'Exam_faccount_loaction_province','Exam_faccount_location_city','Exam_faccount_location_county',
'Exam_maccount_loaction_province','Exam_maccount_location_city','Exam_maccount_location_county']

col_new_no_city=['Exam_smoking_1','Exam_leu_clue_cell','Exam_vaccinate_1','Exam_yigan_1'
,'Exam_pressure','Exam_yigan','Exam_vaccinate_others'
,'Exam_bad_pregnancy_result','Exam_vaccinate','Exam_abo_m_o'
,'Exam_drinking_1','Exam_dysmenorrhea','Exam_fengzhen_1','Exam_fengzhen'
,'Exam_pressure_1','Exam_hbs_ab_1'
,'Exam_child_ill','Exam_rv_igg','Exam_baby_num','Exam_hbs_ab'
,'Exam_bmod_result_type','Exam_leuph'
,'Exam_enou_month_num','Exam_cv_igg','Exam_fnationalty','Exam_mnationality'
,'Early_pregnancy_fola_method','Exam_mjob','Exam_medu_level'
,'Exam_breed_history','Exam_leu_cleanliness','Exam_fedu_level'
,'Exam_contracept_period','Exam_smoking_box_1','Exam_fjob'
,'Exam_first_time_age','Exam_pre_num','Exam_live_birth_num'
,'Early_pregnancy_hcg','Exam_mens_cycle_max','Exam_mens_period_max'
,'Exam_be','Exam_bb','Exam_mens_period','Exam_mens_cycle'
,'Early_pregnancy_sure_mens_time','Exam_low_blood_pressure','Exam_height'
,'Exam_bm','Exam_height_1','Exam_low_blood_pressure_1'
,'Exam_hight_blood_pressure','Early_pregnancy_bresult'
,'Exam_hight_blood_pressure_1','Exam_weight_1','Exam_heart_rate'
,'Exam_weight','Exam_heart_rate_1','Exam_right_orchis_palpable_capacity'
,'Exam_left_orchis_palpable_capacity','Early_pregnancy_folacin','Exam_alt'
,'Exam_bmi_1','Exam_midcell','Exam_alt_1','Exam_bmi','Exam_bwbc'
,'Exam_blood_sugar','Exam_cr_1','Exam_bhb','Exam_bplt','Exam_cr','Exam_tsh'
,'Exam_bn','Exam_m_age','Exam_bl','Exam_f_age','Exam_brbc'
,'Exam_faccount_loaction_province','Exam_maccount_loaction_province'
,'Exam_address_province','Exam_province']

'''
'''

use_col = ['Early_pregnancy_folacin',
'Exam_bhb',
'Exam_bl',
'Exam_smoking_1',

'Exam_contracept_period',
'Exam_faccount_type',
'Exam_pre_num',
'Exam_low_blood_pressure',
'Exam_drinking_1',
'Early_pregnancy_hcg',
'Exam_leu_amine_odor',

'Exam_f_age',
'Exam_bad_pregnancy_result',

'Exam_alt',
'Exam_live_birth_num',
'Exam_prepuce',


'Exam_intrauterine_device',

'Exam_maccount_type',

'Exam_vervix',
'Exam_secretions',
'Exam_hbs_ab',
'Exam_second_hand_smoking',
'Exam_hbs_ab_1',
'Exam_bplt',
'Exam_retardation',
'Exam_be',
'Exam_use_medicine_1',

'Exam_mens_period',
'Exam_leu_trichomonas',

'Exam_dysmenorrhea',
'Exam_use_medicine',
'Exam_sd_child',
'Exam_drinking',

'Exam_pressure',
'Exam_bmod_result_type',
'Exam_economic_pressure_1',

'Exam_mens_cycle_max',
'Exam_halitosis',
'Exam_dead_birth_num',
'Exam_alt_1',
'Exam_other_bad_pregnancy_results_num',
'Exam_economic_pressure',
'Exam_raw_meat_1',

'Exam_drug',
'Exam_hbe_ab_1',
'Exam_thyroid',
'Exam_is_born_ill_1',
'Exam_drug_1',
'Exam_lung',
'Exam_meategg',

'Exam_buge_monggon',
'Exam_tsh',
'Exam_bmi',

'Exam_bm',
'Exam_hbe_ag',
'Exam_abo_f_o',
'Exam_height_1',
'Exam_height',
'Exam_hight_blood_pressure_1',
'Exam_abo_f_a',
'Exam_second_hand_smoking_1',

'Exam_yigan_1',
'Exam_mens_period_max',
'Exam_weight',
'Exam_tense_relationship',
'Exam_pregnancy_ready_1',
'Exam_rh',
'Exam_baby_num',
'Exam_enou_month_num',
'Exam_pubes',
'Exam_mens_cycle',
'Exam_micro_sp',
'Exam_hbe_ag_1',
'Exam_cv_igg',
'Exam_yigan',
'Exam_abo_f_ab',
'Exam_abo_f_b',
'Exam_weight_1',
'Exam_rv_igg',
'Exam_intermarry',
'Exam_cr',
'Exam_indu_abor_num',

'Exam_pregnancy_ready',
'Exam_leu_clue_cell',
'Exam_bwbc',
'Exam_uterus_size_big',
'Exam_short_mouth_num',
'Exam_leu_cleanliness',
'Exam_breed_history',
'Exam_menses_regular',
'Exam_bn',
'Exam_leuph',
'Exam_tense_relationship_1',

'Early_pregnancy_fola_method',

'Early_pregnancy_bresult',
'Early_pregnancy_sure_mens_time',
'Exam_first_time_age',
'Exam_midcell',
'Exam_left_orchis_palpable_capacity',
'Exam_is_ill',
'Exam_is_ill_1',
'Exam_contracept',
'Exam_disease_history_f',
'Exam_disease_history_f_1',
'Exam_address_province',
'Exam_faccount_loaction_province',
'Exam_maccount_loaction_province',
'Exam_fnationalty',
'Exam_mnationality','Exam_province',
'Exam_address_city','Exam_address_county',
'Exam_faccount_location_city','Exam_faccount_location_county',
'Exam_maccount_location_city','Exam_maccount_location_county',
]

use_col_no_city = ['Early_pregnancy_folacin',
'Exam_bhb',
'Exam_bl',
'Exam_smoking_1',

'Exam_contracept_period',
'Exam_faccount_type',
'Exam_pre_num',
'Exam_low_blood_pressure',
'Exam_drinking_1',
'Early_pregnancy_hcg',
'Exam_leu_amine_odor',

'Exam_f_age',
'Exam_bad_pregnancy_result',

'Exam_alt',
'Exam_live_birth_num',
'Exam_prepuce',


'Exam_intrauterine_device',

'Exam_maccount_type',

'Exam_vervix',
'Exam_secretions',
'Exam_hbs_ab',
'Exam_second_hand_smoking',
'Exam_hbs_ab_1',
'Exam_bplt',
'Exam_retardation',
'Exam_be',
'Exam_use_medicine_1',

'Exam_mens_period',
'Exam_leu_trichomonas',

'Exam_dysmenorrhea',
'Exam_use_medicine',
'Exam_sd_child',
'Exam_drinking',

'Exam_pressure',
'Exam_bmod_result_type',
'Exam_economic_pressure_1',

'Exam_mens_cycle_max',
'Exam_halitosis',
'Exam_dead_birth_num',
'Exam_alt_1',
'Exam_other_bad_pregnancy_results_num',
'Exam_economic_pressure',
'Exam_raw_meat_1',

'Exam_drug',
'Exam_hbe_ab_1',
'Exam_thyroid',
'Exam_is_born_ill_1',
'Exam_drug_1',
'Exam_lung',
'Exam_meategg',

'Exam_buge_monggon',
'Exam_tsh',
'Exam_bmi',

'Exam_bm',
'Exam_hbe_ag',
'Exam_abo_f_o',
'Exam_height_1',
'Exam_height',
'Exam_hight_blood_pressure_1',
'Exam_abo_f_a',
'Exam_second_hand_smoking_1',

'Exam_yigan_1',
'Exam_mens_period_max',
'Exam_weight',
'Exam_tense_relationship',
'Exam_pregnancy_ready_1',
'Exam_rh',
'Exam_baby_num',
'Exam_enou_month_num',
'Exam_pubes',
'Exam_mens_cycle',
'Exam_micro_sp',
'Exam_hbe_ag_1',
'Exam_cv_igg',
'Exam_yigan',
'Exam_abo_f_ab',
'Exam_abo_f_b',
'Exam_weight_1',
'Exam_rv_igg',
'Exam_intermarry',
'Exam_cr',
'Exam_indu_abor_num',

'Exam_pregnancy_ready',
'Exam_leu_clue_cell',
'Exam_bwbc',
'Exam_uterus_size_big',
'Exam_short_mouth_num',
'Exam_leu_cleanliness',
'Exam_breed_history',
'Exam_menses_regular',
'Exam_bn',
'Exam_leuph',
'Exam_tense_relationship_1',

'Early_pregnancy_fola_method',

'Early_pregnancy_bresult',
'Early_pregnancy_sure_mens_time',
'Exam_first_time_age',
'Exam_midcell',
'Exam_left_orchis_palpable_capacity',
'Exam_is_ill',
'Exam_is_ill_1',
'Exam_contracept',
'Exam_disease_history_f',
'Exam_disease_history_f_1',
'Exam_address_province',
'Exam_faccount_loaction_province',
'Exam_maccount_loaction_province',
'Exam_fnationalty',
'Exam_mnationality','Exam_province']

'''
'Exam_abnormalflag_leu',
'Exam_abnormalflag_urine_routine',
'Exam_abnormalflag_alt_1',
'Exam_abnormalflag_microsp',
'Exam_abnormalflag_cvigg',
'Exam_abnormalflag_tsh',
'Exam_abnormalflag_urine_routine_1',
'Exam_abnormalflag_rh',
'Exam_abnormalflag_blood',
'Exam_abnormalflag_blood_sugar',
'Exam_abnormalflag_rvigg',
'Exam_abnormalflag_cr',

'''
